### ISSUE TITLE
请问如何让文字始终显示在屏幕上不被清除

### ISSUE THREAD

**Issue by imcloud** [scarsty/jysdl-bh#4]
有一些信息我希望常态化永久显示在屏幕上，
尤其是在战斗中

但战斗代码里充满了清理屏幕的操作 使得这个想法很难实现，
除非我在每一个清理方法后面追加重新绘制文字，但这种方式显然不可取 代码上也会很丑

有什么办法能让文字始终在屏幕上显示呢？

就类似于Photoshop的图层概念，我在普通图层的操作不要影响我文字图层

**Comment by scarsty** [comment]
只能改写画地图的部分了

**Comment by imcloud** [comment]
> 只能改写画地图的部分了

那请问画地图的代码大致去哪里找，在lua层还是c层

**Comment by scarsty** [comment]
可能是c里面mmap最后一个函数

**Comment by imcloud** [comment]
非常感谢解答。
仔细查了项目代码，在lua发现了WarDrawMap函数，这个函数最终调用的就是你说的c层的
绘制地图

而这个函数就是如我所说，在每一个需要重新绘制的时机被调用一次

整个游戏共享一个画布，并没有偷懒的办法

想实现我的需求也要如此 在每一次屏幕被清理时立即补上绘制

**Comment by imcloud** [comment]
> 非常感谢解答。
> 仔细查了项目代码，在lua发现了WarDrawMap函数，这个函数最终调用的就是你说的c层的
> 绘制地图
> 
> 而这个函数就是如我所说，在每一个需要重新绘制的时机被调用一次
> 
> 整个游戏共享一个画布，并没有偷懒的办法
> 
> 想实现我的需求也要如此 在每一次屏幕被清理时立即补上绘制

现在已经大致掌握了此工程，学会了如何控制插入自己的绘制内容，看之前自己的错误言论有点好笑。
有同样需求的朋友可以私信我
